---
- hosts: c1
  tasks:

   - name: Make sure that we can connect to the machine
     ping:

   - name: execute pwd command
     command:
       cmd: pwd
     args:
       chdir: /home/ertan
     register: mypwd

   - name: create a password via openssl
     command:
      cmd: openssl rand -hex 7
     register: mypass

   - name: write my pass variable
     debug: 
        msg: "my pwd is {{mypwd.stdout}} and my pass you created in yaml {{mypass.stdout}}"