---
- hosts: c1

  tasks:

   - name: Execute the command in remote shell
     shell: ./bScript.sh
     args:
       chdir: "/home/ertan"
     register: myhostname
     tags: myhostname
     changed_when: False

   - name: write my pass variable
     debug:
      msg: "myhostname is {{ myhostname.stdout }}"
