---
- hosts: c1
  tasks:

   - name: Execute the command in remote shell
     shell: bScript.sh
     register: myhostname

   - name: write my pass variable
     debug: 
        msg: "myhostname is {{myhostname.stdout}}"
