---
- hosts: c1
  tasks:

   - name: Execute the command in remote shell; stdout goes to the specified file on the remote
     ansible.builtin.shell: /home/ertan/bScript.sh
     register: myhostname

   - name: write my pass variable
     debug: 
        msg: "myhostname is {{myhostname.stdout}}"
