---
- hosts: c1
  become: yes

  tasks:
   - name: Execute the command in remote shell
     shelll: /home/ertan/bScript.sh
     register: myhostname
     changed_when: False

   - name: write my pass variable
     debug:
      msg: "myhostname is {{ myhostname.stdout }}"
