---
- hosts: win
  tasks:
    - name: My first winrm ping
      win_ping:

    - name: My second
      shell:
          executable: pwd
      register: foo
      tag: secondping

    - debug: msg=foo
