---
- hosts: win 
  gather_facts: false

  tasks:
    - name: My first winrm ping
      win_ping:

    - name: Run a command under a non-Powershell interpreter (cmd in this case)
      win_shell: echo %WINDIR%
      args: 
        executable: cmd
      register: homedir_out
      tags:
        - wins

    - debug:
        msg: "{{ homedir_out }}"