---
- hosts: man
  tasks:

   - name: Make sure that we can connect to the machine
     ping:

   - name: removed 
     yum:
       name: "{{ item }}"
       state: removed
     loop:
      - net-tools
      - vim
     become: true

   - name: Installed
     yum:
       name: "{{ item }}"
       state: present
       update_cache: true
     loop:
       - vi
       - telnet
     become: true
